name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
          with:
            python-version: 3.12

        - name: Run tests
          run: |
            uv run pytest --cov --cov-report=xml

        - name: Upload results to Codecov
          uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
